#!/bin/bash
#
# Pass in the name of the file to add the code to
buildAnsibleHostsFile() {
    local ansfile=$1
    cat <<-EOF > ${ansfile}
[all:vars]
ansible_user=ansible
ansible_become=true
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'

[all]
EOF

}



